version: '3'

services:
  postgres:
    container_name: db
    image: postgres:11-alpine
    ports:
      - 8001:5432
    env_file:
      - '../../.env'
    networks:
      shop40:
    volumes:
      - '~/dbdata:/var/lib/postgresql/data'
    restart: unless-stopped
  
  web:
    container_name: shop40
    image: shop:40
    build: 
      context: ../../
    env_file:
      - '../../.env'
    environment:
      - IN_DOCKER=true
    networks: 
      shop40:
    ports:
      - 8002:80
      - 5678:5678
    command: gunicorn -b 0.0.0.0:80 shop40.app:api --reload --timeout 120 --log-level debug
    volumes:
      - ../../:/shop40
    depends_on:
      - postgres
    restart: unless-stopped
  
networks:
  shop40: 