version: '3'

services:
  postgres:
    container_name: db
    image: postgres:11-alpine
    ports:
      - 8001:5432
    env_file:
      - '../../shop40.env'
    networks:
      shop40:
    volumes:
      - '~/shop40/data:/var/lib/postgresql/data'
    restart: unless-stopped
  
  web:
    container_name: shop40
    image: ../../
    env_file:
      - '../../shop40.env'
    environment:
      - TESTING=true
      - SENDGRID_API_KEY=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
    networks: 
      shop40:
    ports:
      - 8002:80
    command: gunicorn -b 0.0.0.0:80 shop40.app:api --reload
    volumes:
      - /shop40/code:/shop40
    depends_on:
      - postgres
    restart: unless-stopped
  
networks:
  shop40: 